version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: itq-postgres
    environment:
      POSTGRES_DB: itqdocs
      POSTGRES_USER: itq
      POSTGRES_PASSWORD: itq
    ports:
      - "5432:5432"
    volumes:
      - itq-postgres-data:/var/lib/postgresql/data

volumes:
  itq-postgres-data:
